# Generated by Django 3.2.9 on 2021-12-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp32', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='esp',
            name='password',
            field=models.TextField(default=3854),
            preserve_default=False,
        ),
    ]
